name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code từ repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Thiết lập Java và Maven
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: "23"
          distribution: "temurin"

      # Build JAR
      - name: Build with Maven
        run: mvn clean package

      # Upload JAR to Release
      - name: Upload JAR to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: target/*.jar
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
